### PR TITLE
Update Vite version 4.5.0 -> 5.0.11

### LINKED ISSUE #87: Enhancement: Vite XSS Vulnerability
### Describe the Current Behavior/Feature:

Screen Shot 2024-01-03 at 2 06 13 PM

Update Vite version to close XSS vulnerability recorded in the last npm audit run.

---

### Proposed Implementation:

npm audit fix 😎

### PR DESCRIPTION
**Pull request by ogorman89**
## This PR:

Resolves #87 by updating Vite version

---

## Screenshots (if applicable):

N/A

---

## Future Steps/PRs Needed to Finish This Work (optional):

None

### CODE REVIEW

**Comment by andycwilliams** [comment]
Don't have time to open up my editor atm. But shouldn't `package.json` also be updated?

**Comment by ogorman89** [comment]
@andycwilliams good idea, I will update the required Vite version today in `package.json` to ^4.5.1

**Comment by ogorman89** [comment]
@andycwilliams, thanks for catching that. It's been corrected 😎

**Comment by xscottxbrownx** [comment]
I haven't studied this much...

Do we need `vite` in both `dependencies` and `devdependencies`?
If so, should they be the same version?

**Comment by andycwilliams** [comment]
When I look in the coding sandbox by clicking on "react" in the [vite website](https://vitejs.dev/guide/) (underneath "Trying Vite Online"), it lists vite solely in `devDependencies`.

Also, it looks like the latest version is now `5.0.10`:
https://www.npmjs.com/package/vite

**Comment by ogorman89** [comment]
> When I look in the coding sandbox by clicking on "react" in the [vite website](https://vitejs.dev/guide/) (underneath "Trying Vite Online"), it lists vite solely in `devDependencies`.
> 
> Also, it looks like the latest version is now `5.0.10`: https://www.npmjs.com/package/vite

Thanks @andycwilliams

### These changes are in: 
- Updated `vite` to 5.0.11
- Removed vite from `dependencies` so it is now only in `devDependencies`
- Also updated `vitejs/plugin-react-swc` to the latest version 3.5.0

In response to @xscottxbrownx, yes, they should be the same lol, but Vite isn't needed in dependencies, so I removed it.

**Review by andycwilliams — APPROVED** [review]
Good to go 😎

**Pull request merged**
