### PR TITLE
creating 404 page

### LINKED ISSUE #26: Create basic 404 page
### Figma link for component:

None designed yet.

---

### Feature Description:

Creating a 404 page w/ button to navigate back.

---

### Proposed Solution:

Currently, idea is just to have a centered card that says "Page not found" and a button labeled "go back" that works just like browser back button.

---

### Alternative Solutions:

Team discussion and design.

---

### Screenshots (if applicable):

Something to start with like this:
Screenshot 2023-10-22 at 8 24 17 PM

Then, open up for discussion.

### PR DESCRIPTION
**Pull request by xscottxbrownx**
## This PR:

Resolves #26

---

## Screenshots:

https://github.com/codeforpdx/codepdx_website/assets/71395931/af49fa4b-4b61-4515-9ff2-6320e3ffd050

---

## Future Steps/PRs Needed to Finish This Work:

Any discussion/feedback on style, content, etc...

### CODE REVIEW

**Review by Jared-Krajewski — APPROVED** [review]
🚀

**Comment by xscottxbrownx** [comment]
> 🚀

should this be a card, or more like large hero landing page?  photo across full background and text/button on top?

**Comment by Jared-Krajewski** [comment]
> should this be a card, or more like large hero landing page? photo across full background and text/button on top?

Generally I think they are a full page. having nav and footer in seems optional. Personally I think a full page would look better over a card but we had no design and this works for now.

**Review by andycwilliams — APPROVED** [review]
Good to go for me. We can discuss UX more but that may take some time and I'd like to get this in place soon.

**Pull request merged**
