### PR TITLE
Issue 7b/create volunteer page 2

### LINKED ISSUE #7: Create Volunteer Page
### Feature Description:
Create the contribution chart for new members including:
- Steps 1 through 4
- Additional Onboarding Info
- Link graphic

---

### Screenshots:
Capture

---
### Additional Context:
[Link to Navbar in Figma](https://www.figma.com/file/QWycOkxNJmtiyZ3v8imIzx/Code-PDX-website?type=design&node-id=132-275&mode=design&t=JhDPDVeP1SwPMWwa-4)

### PR DESCRIPTION
**Pull request by xscottxbrownx**
## This PR:

Resolves #7 

#### Testing a different package (react-vertical-timeline.) Take a look at this new branch and give any feedback. 

Still need to go in and clean up code. Most likely make a `createListItem` function, an array of the data, and map it to create the elements.

---

## Screenshots:

https://github.com/codeforpdx/codepdx_website/assets/71395931/094bfc84-2db9-4b0a-94b6-ac844b82da25

---

#### Just overall feedback on direction, and any thoughts.

On mobile, think going to make gradient all same direction (gray on left) so point of box is more visible.

### CODE REVIEW

**Comment by andycwilliams** [comment]
Very smooth looking. Definitely better than the `Stepper` imo. I have some thoughts on smaller edits (margins, font size, etc.) but if you're only looking for general feedback then those can probably wait.

As for the gradient, so far on mobile views we're doing from top to bottom, not one side to another.

Although, I'm not 100% sure whether gradient boxes are necessary. On desktop it looks fine enough, just like in the Figma. For mobile it may be nice to distinguish the steps more, but then it'd be inconsistent...I'll have to think about it more. 

I also don't know how closely we need to adhere to the Figma in terms of the steps themselves. With that, they're not number and have small branches to each side, which I like. A single, numbered line also works. Right now I lean towards the former.

**Comment by Jared-Krajewski** [comment]
@andycwilliams  the branches were far too time consuming to make so they arent happening, this is why we arrived at the methods he is trying. 

@xscottxbrownx All of the following comments can be saved for Wednesday and I am Ok merging this in before the meeting after your code cleanup (or before if you don't have time). updates can come in a new issues/PR. 

1. Even tho it allows it i think the section headers should be in the box with the content or right above it , I feel like it makes each card stand out/pop a bit more maybe even use that line that was added to project cards. 

2. 2nd on what  Andy said about mobile background going up or down or rotating or being solid, they cut the text weird on mobile. Or we could put each step in a blob as the box to make this page have some extra character. (we can play with that on figma at meeting)

-  (3)or the ones with many steps they should probably start with a bullet , a `-`  , or a number. I feel like it makes it easier to keep steps separated when reading. 

4. more mobile adjustments to let text spread wider.

**Comment by xscottxbrownx** [comment]
@andycwilliams @Jared-Krajewski 

### updated... see if you have any feedback when you have time.

---

In `src > pages > Volunteer.jsx`:
you can switch `<VolunteerSteps>` & `<VolunteerSteps2>` to see the minimal difference. 

Version 2 is refactored, but I have yet to figure out how to make the colored links exactly like `<VolunteerSteps>`.

P.S. I would prefer to pull the `VolunteerStepsData` out into it's own file, but I think the rest could stay.

**Comment by Jared-Krajewski** [comment]
code wise: not going to dig into this too much because it will change by tomorrow, Just the console error for list items needing keys. 

I don't see a ton of styling difference on the links. maybe I'm missing what you are referring to. lets get this merged at whatever state its in before the meetup either way. I think this is a great start after we had to ditch the other design. After the meeting we will be able to quickly cover what this needs as a group and add whatever design input everyone wants  

I'm sure a few things on this page will change after the meeting anyways. I

I'd also like to see the extra text about assigning roles on discord left in but up for discussion either way.  

- steps 1
   Steps1


- steps 2
   Screenshot 2023-11-07 at 10 03 17 PM

**Comment by xscottxbrownx** [comment]
Ok,

so current plan is to see about getting feedback and having this PR merged in before tonight's meeting (so we can work cleanly from `main` branch.)

I plan on leaving the two versions of `VolunteerSteps` in here, unless somebody can figure out the link issue (VolunteerSteps2 currently can only create the link at the end of the sentence, where VolunteerSteps has link wherever placed - as it's all manual and not a .map() )

& I plan on keeping this branch even if it does get merged before meeting, so can make any changes we come up with at meeting.

-----

Willing to change above plan if needed/desired.

**Review by Jared-Krajewski — APPROVED** [review]
🤠 Ok with this going in for second review with everything else unless you want to try to get it perfect on this one. Thats your call. 

I think adding a borderRadius to the cards will keep it consistent with the rest of the site.

Screenshot 2023-11-09 at 9 39 03 AM


Id like to trim some of the mobile padding, currently there is 64px total to the left and 48px to the right of text that eats up most of mobile screen width. Might also consider removing the bullets/numbers on mobile if we need more width for text.

https://github.com/codeforpdx/codepdx_website/assets/114430929/718a3fbb-9360-4607-80f5-f3f5b31faaeb

 I know you had mentioned the small pointers to the numbers on each line element. Did you want those? I'm ok with `contentArrowStyle` being removed. 

Screenshot 2023-11-09 at 9 17 09 AM
Screenshot 2023-11-09 at 9 17 35 AM

**Review by andycwilliams — APPROVED** [review]
🤠🤠

**Pull request merged**
