### PR TITLE
Issue 105/rotate volunteer images

### LINKED ISSUE #105: Enhancement: Rotate volunteer images on home page
### Describe the Current Behavior/Feature:

- Make Flo and Hugh images static (Top two images)
- Rotate other members from the `volunteers` folder
Screenshot 2024-01-31 at 2 44 31 PM

---

### Proposed Implementation:

Make a function that loads the bottom three images randomly.

### PR DESCRIPTION
**Pull request by andycwilliams**
## This PR:

Resolves #105 

Adds function that shuffles the bottom three images upon page reload. The top two remain static.

---

## Screenshots (if applicable):

[video (1).webm](https://github.com/codeforpdx/codepdx_website/assets/83156697/d76b8f00-5cd2-476e-968f-19c87ae1daeb)

(Shuffling demonstration begins after a few seconds)

### CODE REVIEW

**Review by Jared-Krajewski — CHANGES_REQUESTED** [review]
styling needs to maintain consistency when images load.

**Comment by andycwilliams** [comment]
> styling needs to maintain consistency when images load.

Please elaborate.

**Comment by Jared-Krajewski** [comment]
> > styling needs to maintain consistency when images load.
> 
> Please elaborate.


Screenshot 2024-02-19 at 8 01 10 AM
Screenshot 2024-02-19 at 8 01 56 AM


The images will need to be inside of a container that limits their size for consistency, with this update, images rotating load to whatever size the image is and in any position. Currently it was just sized by the images but wasn't as big of a deal because they were static and it maintained its styling because of that. We would want to maintain the two square images with a longer middle one.

**Comment by andycwilliams** [comment]
Unassigning myself from this but leaving open the PR. The branch can be taken over, if anyone wants to take it on.

**Pull request closed without merging**
