### PR TITLE
Minor initial launch adjustments

### LINKED ISSUE #93: Enhancement: Adjustments for initial deployment
### Describe the Current Behavior/Feature:

This issue is a collection of small adjustments needed so we can get the initial site hosted.

---

### Proposed Implementation:

Per @Jared-Krajewski :
- remove the tags that house the logo. I was just going to comment them out so they can get tuned in the future
- remove Epicodus from `secondarySponsors`
- comment out the dark mode toggle until it is ready
- add "Home" to `navbar`

### PR DESCRIPTION
**Pull request by ogorman89**
## This PR:

Resolves #93 

- Commented out blobs behind the logo in the `nav` and `footer`
- Remove Epicodus from `secondarySponsors` and removed their logos from `public/assets/partnerLogos`
- Commented out the dark mode toggle and related imports and styling
- Added a `Home` link to `nav`, renamed the aria-label on the CODE PDX logo to 'CODE PDX' so there weren't two links with a `Home` aria-label 

---

## Screenshots (if applicable):

Screen Shot 2024-01-23 at 10 14 38 AM

Screen Shot 2024-01-23 at 10 16 37 AM

---

## Future Steps/PRs Needed to Finish This Work (optional):

Once we get the site hosted and finish darkmode we can re-enable the darkmode toggle and add the logo blobs back if desired.

### CODE REVIEW

**Comment by andycwilliams** [comment]
I'm not sure #78 merged correctly, since `SecondaryPartners.jsx` was somehow reverted to before the changes were made. Still investigating, so I don't know if that's the only file affected. Point being, that component at least is out of date. I dug up the fixed version and can share that.

Otherwise, the logo in the navbar doesn't contrast very much. Dunno if it'd be too cumbersome to find a workaround and not just fix the blobs.

And let me know if you think it'd be good to add the new EmailJS keys in this PR or if I should just create a new one.

**Comment by Jared-Krajewski** [comment]
> I'm not sure #78 merged correctly, since `SecondaryPartners.jsx` was somehow reverted to before the changes were made. Still investigating, so I don't know if that's the only file affected. Point being, that component at least is out of date. I dug up the fixed version and can share that.
> 
> Otherwise, the logo in the navbar doesn't contrast very much. Dunno if it'd be too cumbersome to find a workaround and not just fix the blobs.
> 
> And let me know if you think it'd be good to add the new EmailJS keys in this PR or if I should just create a new one.

It looks like you merged over your changes when you merged main in. I will touch up any changes that need to be done to go live for tomorrow after Ians Merge and we can go over anything else at the next work session or on discord sometime to figure out what we have left. 

Screenshot 2024-01-23 at 4 48 22 PM

**Review by Jared-Krajewski — APPROVED** [review]
Thanks for doing that so quick.

**Comment by ogorman89** [comment]
> I'm not sure #78 merged correctly, since `SecondaryPartners.jsx` was somehow reverted to before the changes were made. Still investigating, so I don't know if that's the only file affected. Point being, that component at least is out of date. I dug up the fixed version and can share that.
> 
> Otherwise, the logo in the navbar doesn't contrast very much. Dunno if it'd be too cumbersome to find a workaround and not just fix the blobs.
> 
> And let me know if you think it'd be good to add the new EmailJS keys in this PR or if I should just create a new one.

If you have what you need to update the emailJS stuff can you push that to a separate PR? I'm merging this one.

**Pull request merged**
